title: Benson.O
description: AI Infrastructure + Agent Product Architect
url: "https://superobk.github.io"
baseurl: ""
theme: minima
author:
  name: Benson.O
  github: superobk
  linkedin: bensonou
plugins:
  - jekyll-seo-tag
  - jekyll-feed
markdown: kramdown
permalink: pretty
